// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtbODQZd-XAPATWQ4zDUTJ4nJUBRDIic8',
    appId: '1:844068722646:web:dfa61c3a5dc1453ed5f677',
    messagingSenderId: '844068722646',
    projectId: 'emergency--sos-app',
    authDomain: 'emergency--sos-app.firebaseapp.com',
    storageBucket: 'emergency--sos-app.firebasestorage.app',
    measurementId: 'G-4Y9LTE7S7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO2uMT7eh3i1TBRTStaI9Dh14d9pETNfQ',
    appId: '1:844068722646:android:59c658b9d2da37c5d5f677',
    messagingSenderId: '844068722646',
    projectId: 'emergency--sos-app',
    storageBucket: 'emergency--sos-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtbODQZd-XAPATWQ4zDUTJ4nJUBRDIic8',
    appId: '1:844068722646:web:ac599391a21a8c99d5f677',
    messagingSenderId: '844068722646',
    projectId: 'emergency--sos-app',
    authDomain: 'emergency--sos-app.firebaseapp.com',
    storageBucket: 'emergency--sos-app.firebasestorage.app',
    measurementId: 'G-QV6GLY85EN',
  );
}
